# df.shift(n)

In [62]:
import pandas as pd
import numpy as np

s = pd.Series([1,3,5,np.nan,6,8])

print(s)
print(s.shift(2))

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
0    NaN
1    NaN
2    1.0
3    3.0
4    5.0
5    NaN
dtype: float64


In [71]:
import pandas as pd

a = pd.Series([1,2,4,7,11,16])
b = a - a.shift(1)

print(b.values[-1]*1.0)
print(b*1)

5.0
0    NaN
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
dtype: float64


# Delete a column or row

In [37]:
import pandas as pd
import numpy as np

df = pd.DataFrame({"A":[1,2], "B":[3,4], "C":[5,6]})
print (df)

print('\n drop a column')
print(df.drop("A", axis=1))


print('\n drop a row')
print(df.drop(0))


   A  B  C
0  1  3  5
1  2  4  6

 drop a column
   B  C
0  3  5
1  4  6

 drop a row
   A  B  C
1  2  4  6


# dimension of a dataframe
* size

* count()

* shape

In [31]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.array(np.random.randn(2,3)))
print('df:\n',df)
print('size:\n',df.size)
print('count:\n',df.count())
print('count:\n',df.count)
print('shape:\n',df.shape)

df:
           0         1         2
0 -1.421417 -0.134520 -0.200315
1  0.093646 -0.284435 -0.933443
size:
 6
count:
 0    2
1    2
2    2
dtype: int64
count:
 <bound method DataFrame.count of           0         1         2
0 -1.421417 -0.134520 -0.200315
1  0.093646 -0.284435 -0.933443>
shape:
 (2, 3)


# ix

DataFrame.ix
A primarily label-location based indexer, with integer position fallback.

.ix[] supports mixed integer and label based access. It is primarily label based, but will fall back to integer positional access unless the corresponding axis is of integer type.

.ix is the most general indexer and will support any of the inputs in .loc and .iloc. .ix also supports floating point label schemes. .ix is exceptionally useful when dealing with mixed positional and label based hierachical indexes.

However, when an axis is integer based, ONLY label based access and not positional access is supported. Thus, in such cases, it’s usually better to be explicit and use .iloc or .loc.


In [73]:
import pandas as pd

data = {'key': ['B','D','C','A'], 'value':[1,2,3,4]}
print(data)

sub_sort = pd.DataFrame.from_dict(data).sort(columns=['key'])
print(sub_sort)

sub_ix = sub_sort.ix[0:1] # ?? label based access
print(sub_ix)
print(sub_ix.value.mean()) #2.0


sub_sort.index = ['a', 'b','c','d']
print(sub_sort.ix[0:1])
print(sub_sort.ix[0:1].value.mean())


                                  

{'key': ['B', 'D', 'C', 'A'], 'value': [1, 2, 3, 4]}
  key  value
3   A      4
0   B      1
2   C      3
1   D      2
  key  value
0   B      1
2   C      3
1   D      2
2.0
  key  value
a   A      4
4.0


C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:6: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)


TypeError: unhashable type: 'slice'

# Indexing
df[0,:]   #TypeError: unhashable type: 'slice'

* iloc: by position, similar to array

* loc: by label, end index is included

* ix: by label-position, end index is included


In [79]:
import pandas as pd

data = {'key': ['B','D','C','A'], 'value':[1,2,3,4]}

df = pd.DataFrame(data)
print(x)
# df[0,:]   #TypeError: unhashable type: 'slice'

print(x.ix[0,:])
print(x.iloc[0,:])

print(x.loc[0,:])

print(x.loc[1:1, :])

  key  value
0   B      1
1   D      2
2   C      3
3   A      4
key      B
value    1
Name: 0, dtype: object
key      B
value    1
Name: 0, dtype: object
key      B
value    1
Name: 0, dtype: object
  key  value
1   D      2


In [82]:
import pandas as pd
df = pd.DataFrame([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10), (11, 12, 13,
14, 15)])

# end position is included
print (df.ix[1:2,3:4])
print(df.loc[1:2,3:4])

# end position is not included, like array slicing
print(df.iloc[1:2,3:4])

    3   4
1   9  10
2  14  15
   3
1  9
    3   4
1   9  10
2  14  15


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

print (np.random.randn(10, 4).cumsum(0))
df = pd.DataFrame(np.random.randn(10, 4).cumsum(0), columns=['A',
'B', 'C', 'D'], index=np.arange(0, 100, 10))
df.plot()
plt.show()

[[ 0.30506413 -0.91616889 -1.58557942 -0.02254205]
 [-0.22024793 -3.34067457 -1.2141001  -1.32667958]
 [-0.94306054 -6.75318724 -1.25983958 -1.17323708]
 [-0.734237   -5.57552192 -1.05947204 -0.88455994]
 [-0.77374134 -5.62394325 -1.63524346 -0.92300051]
 [-1.47565807 -5.72891908 -1.30984616 -0.84120146]
 [-3.09128456 -6.37347504 -1.76035175 -0.60650765]
 [-3.62718458 -4.88899082 -1.33730567 -2.22652019]
 [-4.49152054 -5.35893587 -1.56173189 -0.95825018]
 [-5.83947162 -5.96606337 -1.77905718 -1.86472228]]
